name: docker

on:
  push:
    branches:
      - main
      - github-ci

jobs:
  build_docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.0
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive
      - run: ./build_docker.sh
