name: local

on:
  push:
    branches:
      - main
      - github-ci

jobs:

  ############################################
  #            Build                         #
  ############################################

  build_docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Build fuzzware
        uses: actions/checkout@v3.0.0
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive
      - run: ./install_local.sh