name: local

on:
  push:
    branches:
      - main
      - github-ci

jobs:

  ############################################
  #            Build                         #
  ############################################

  build_docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.0
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt-get update && apt-get upgrade -y && sudo apt-get install -y python python3 python3-pip automake tmux redis wget autoconf sudo htop cmake clang vim unzip git binutils-arm-none-eabi
          pip3 install virtualenv virtualenvwrapper cython setuptools
      - run: ./install_local.sh