name: local

on:
  push:
    branches:
      - main
      - github-ci

jobs:

  ############################################
  #            Build                         #
  ############################################

  build_local:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.0
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y python python3 python3-pip automake tmux redis wget autoconf sudo htop cmake clang vim unzip git binutils-arm-none-eabi
          pip3 install virtualenv virtualenvwrapper cython setuptools
      - uses: actions/cache@v3
        with:
          path: /home/runner/.virtualenvs/
          key: ${{ runner.os }}-virtualenvs
      - run: ./install_local.sh
      - uses: actions/cache@v3
        with:
          path: /home/runner/.virtualenvs/
          key: ${{ runner.os }}-virtualenvs
  ############################################
  #            Fuzzing                       #
  ############################################

  fuzzing_ARCH_PRO_docker:
    runs-on: ubuntu-20.04
    needs: build_local
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0
      - uses: actions/cache@v3
        with:
          path: /home/runner/.virtualenvs/
          key: ${{ runner.os }}-virtualenvs
      - name: Setup AFL
        run: echo core | sudo tee /proc/sys/kernel/core_pattern
      - name: setup venv
        run: workon fuzzware
      - name: fuzz ARCH_PRO docker
        run: fuzzware pipeline --no-tty --skip-afl-cpufreq --run-for 00:00:00:10 -n 2 ./examples/pw-recovery/ARCH_PRO
      - uses: actions/cache@v3
        with:
          path: examples/pw-recovery/ARCH_PRO/fuzzware-project
          key: ${{ runner.os }}-fuzzware-project-local